CI: azure
boost_cpp: 1.74.0
c_compiler: vs2017
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2017
extend_keys:
- ignore_build_only_deps
- ignore_version
- pin_run_as_build
- extend_keys
fortran_compiler: gfortran
gnuradio_core: 3.9.3
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.18'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
  boost-cpp:
    max_pin: x.x.x
python: 3.8.* *_cpython
r_base: '3.4'
target_platform: win-64
vc: '14'
volk: '2.5'
zip_keys:
- - python
  - numpy
