# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# C:\Users\ggrebel\radioconda\pkgs\gnuradio-iridium-1.0.0\info\recipe, last modified Wed Oct  6 08:03:15 2021
# ------------------------------------------------

package:
  name: gnuradio-iridium
  version: 1.0.0
source:
  #patches:
  #  - 0001-Set-VERSION_PATCH-to-work-around-change-to-GrVersion.patch
  #sha256: a9c980a30b993ae26e58a5bd07fd9c71f573655eaaf5dc64e142e6332977c5c0
  url: https://github.com/yaatcha/gr-iridium/raw/master/gr-iridium.tar.gz
build:
  number: '1'
  run_exports:
    - gnuradio-iridium >=0.0.1,<5.4.0a0
  string: py38hf0e3c0a_1
requirements:
  build:
    - cmake 3.21.3 h39d44d4_0
    - ninja 1.10.2 h2d74725_1
    - ucrt 10.0.20348.0 h57928b3_0
    - vc 14.2 hb210afc_5
    - vs2015_runtime 14.29.30037 h902a5da_5
    - vs2017_win-64 19.16.27038 h2e3bad8_2
    - vswhere 2.8.4 h57928b3_0
  host:
    - boost-cpp 1.74.0 h5b4e17d_4
    - bzip2 1.0.8 h8ffe710_4
    - ca-certificates 2021.5.30 h5b45459_0
    - click 8.0.1 py38haa244fe_0
    - click-plugins 1.1.1 py_0
    - colorama 0.4.4 pyh9f0ad1d_0
    - fftw 3.3.10 nompi_hb424310_101
    - gnuradio-core 3.9.3.0 py38h0268b5b_0
    - gsl 2.7 hdfb1a43_0
    - intel-openmp 2021.3.0 h57928b3_3372
    - libblas 3.9.0 11_win64_mkl
    - libcblas 3.9.0 11_win64_mkl
    - libcodec2 1.0.1 hcd874cb_1
    - libflac 1.3.3 h0e60522_1
    - liblapack 3.9.0 11_win64_mkl
    - libogg 1.3.4 h8ffe710_1
    - libopus 1.3.1 h8ffe710_1
    - libsndfile 1.0.31 h0e60522_1
    - libvorbis 1.3.7 h0e60522_0
    - libzlib 1.2.11 h8ffe710_1013
    - log4cpp 1.1.3 h0e60522_1002
    - lz4-c 1.9.3 h8ffe710_1
    - m2w64-gcc-libgfortran 5.3.0 6
    - m2w64-gcc-libs 5.3.0 7
    - m2w64-gcc-libs-core 5.3.0 7
    - m2w64-gmp 6.1.0 2
    - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
    - mako 1.1.5 pyhd8ed1ab_0
    - markupsafe 2.0.1 py38h294d835_0
    - menuinst 1.4.18 py38haa244fe_0
    - mkl 2021.3.0 hb70f87d_564
    - mpir 3.0.0 he025d50_1002
    - msys2-conda-epoch 20160418 1
    - numpy 1.18.5 py38h72c728b_0
    - openssl 3.0.0 h8ffe710_1
    - pip 21.2.4 pyhd8ed1ab_0
    - pybind11 2.8.0 py38hbd9d945_0
    - pybind11-abi 4 hd8ed1ab_3
    - pybind11-global 2.8.0 py38hbd9d945_0
    - python 3.8.12 h900ac77_1_cpython
    - python_abi 3.8 2_cp38
    - pywin32 301 py38h294d835_0
    - setuptools 58.2.0 py38haa244fe_0
    - six 1.16.0 pyh6c4a22f_0
    - sqlite 3.36.0 h8ffe710_2
    - tbb 2021.3.0 h2d74725_0
    - ucrt 10.0.20348.0 h57928b3_0
    - vc 14.2 hb210afc_5
    - volk 2.5.0 h63175ca_0
    - vs2015_runtime 14.29.30037 h902a5da_5
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h62dcd97_1
    - zlib 1.2.11 h8ffe710_1013
    - zstd 1.5.0 h6255e5f_0
  run:
    - construct >=2.9
    - gnuradio-core >=3.9.3.0,<3.9.4.0a0
    - gnuradio-zeromq
    - log4cpp >=1.1.3,<1.2.0a0
    - matplotlib-base
    - numpy
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
    - pyyaml
    - requests
    - vc >=14.1,<15.0a0
    - volk >=2.5.0,<2.6.0a0
    - vs2015_runtime >=14.16.27012
test:
  commands:
    - if not exist %PREFIX%\\Library\\include\\iridium\\api.h exit 1
    - if not exist %PREFIX%\\Library\\bin\\gnuradio-iridium.dll exit 1
    - if not exist %PREFIX%\\Library\\lib\\gnuradio-iridium.lib exit 1
  imports:
    - iridium
about:
  description: 'gr-iridium is a GNU Radio out-of-tree module iridium.

    '
  dev_url: 
  doc_url: 
  home: 
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A collection of decoders for iridium
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - gg

